name: "Integrate"

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:
  linting:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          python-version: ['3.11']
      steps:
        - uses: actions/checkout@v3

        - name: Set up Python 3
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'

        
        - name: Install Dependencies
          shell: bash
          run: |
            python -m pip install --upgrade pip
            pip install -r src/requirements.txt

        - name: Lint
          shell: bash
          run: |
            pylint src/solver_add.py
            pylint src/solver_substract.py
            pylint src/tests/test_solver_add.py
            pylint src/tests/test_solver_substract.py

  tests:
    name: "Tests"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        python-version:
          - "3.11"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi
      - name: Unit and Integration Tests
        shell: bash
        run: |
          cd src/ && python runner.py && tar -cvf juintreport.tar reports
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: src/juintreport.tar